version: '3.8'

services:
  web:
    build: .
    container_name: accounting_reconciliation_app
    ports:
      - "5000:5000"
    volumes:
      - ./output:/app/output
      - ./log:/app/log
      - ./input:/app/input
    restart: unless-stopped